apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swarmchestrate
labels:
  - pairs:
      app: resource-lead-agent
    includeSelectors: true
resources:
  - clusterrole.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - svc.yaml
  - pvc.yaml
  - cm.yaml
  - deployment.yaml
  - ingress.yaml
images:
  - name: ghcr.io/mahmud2011/swarmchestrate/resource-lead-agent
    newName: ghcr.io/mahmud2011/swarmchestrate/resource-lead-agent
    newTag: 0.1.1
