app:
  type: cloud
  schedulerinterval: 10
  applicationheartbeattimeout: 30
  nodeheartbeattimeout: 15

httpserver:
  port: 8081
  gracefulshutdowntimeout: 5

postgresdb:
  host: localhost
  port: 5432
  user: foo
  pass: pass
  dbname: knowledge_base
  sslmode: disable
  timezone: UTC

raft:
  id: 1
  peers:
    - http://172.18.255.1:8080
    - http://172.18.255.26:8080
