apiVersion: v1
kind: Service
metadata:
  name: resource-lead-agent-lb
  labels:
    app: resource-lead-agent
  annotations:
    metallb.universe.tf/address-pool: kind-cluster
spec:
  type: LoadBalancer
  selector:
    app: resource-lead-agent
  ports:
    - name: raft
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
