# ref: https://github.com/sedflix/multi-cluster-istio-kind
# change addresses as per the output of `docker network inspect -f '{{$map := index .IPAM.Config 0}}{{index $map "Subnet"}}' kind`
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kind-cluster
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.1-172.18.255.25
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kind-cluster
  namespace: metallb-system
