apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-agent
spec:
  replicas: 1
  template:
    metadata:
    spec:
      serviceAccountName: resource-agent
      containers:
        - name: resource-agent
          image: ghcr.io/mahmud2011/swarmchestrate/resource-agent:0.1.0
          imagePullPolicy: Always
          args:
            - resource-agent
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: resource-agent
