CREATE TABLE IF NOT EXISTS applications (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    labels JSONB,
    qos JSONB,
    cloud_svc JSONB,
    cloud_svc_version UUID,
    cloud_svc_cluster UUID,
    cloud_svc_nodes TEXT,
    cloud_svc_status TEXT,
    cloud_svc_heartbeat TIMESTAMPTZ,
    fog_svc JSONB,
    fog_svc_version UUID,
    fog_svc_cluster UUID,
    fog_svc_nodes TEXT,
    fog_svc_status TEXT,
    fog_svc_heartbeat TIMESTAMPTZ,
    edge_svc JSONB,
    edge_svc_version UUID,
    edge_svc_cluster UUID,
    edge_svc_nodes TEXT,
    edge_svc_status TEXT,
    edge_svc_heartbeat TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (cloud_svc_cluster) REFERENCES clusters(id),
    FOREIGN KEY (fog_svc_cluster) REFERENCES clusters(id),
    FOREIGN KEY (edge_svc_cluster) REFERENCES clusters(id)
);
